# Generated by Django 5.0.4 on 2024-05-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
