# Generated by Django 5.0.4 on 2024-05-09 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_user_alter_task_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"is_superuser": False},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
