# Generated by Django 5.0.4 on 2024-05-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("COMPLETED", "COMPLETED"),
                    ("PENDING", "PENDING"),
                    ("DELAYED", "DELAYED"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
